import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
import Image from 'next/image';
import React from 'react';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import AppWalletProvider from '../components/app-wallet-provider';

const geistSans = localFont({
  src: '/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: '/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-100 text-gray-300 antialiased">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <AppWalletProvider>
          <Navbar />
          <main className="min-h-[calc(100vh-7.5rem)] p-8 md:p-12 mt-10 mr-10 ml-10"></main>
          <section>{children}</section>

          <Footer />
        </AppWalletProvider>
      </body>
    </html>
  );
}
